stages:
  - deploy

deploy_to_biznet_gio:
  stage: deploy
  only:
    - main
  before_script:
    - 'which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $BIZ_HOST >> ~/.ssh/known_hosts
  script:
    - ssh $BIZ_USER@$BIZ_HOST <<'EOF'
        set -e
        cd $BIZ_PATH
        git pull origin main
        npm install
        npm run build
        pm2 delete meko-point-web || true
        pm2 start ecosystem.config.js
        pm2 save
      EOF

